---
inspircd_inspircd_power_diepass: "{{ lookup('file', 'secret/inspircd_inspircd_power_diepass') }}"
inspircd_inspircd_power_restartpass: "{{ lookup('file', 'secret/inspircd_inspircd_power_restartpass') }}"
inspircd_links_madhax_recvpass: "{{ lookup('file', 'secret/inspircd_links_madhax_recvpass') }}"
inspircd_links_madhax_sendpass: "{{ lookup('file', 'secret/inspircd_links_madhax_sendpass') }}"
inspircd_links_minecraft_recvpass: "{{ lookup('file', 'secret/inspircd_links_minecraft_recvpass') }}"
inspircd_links_minecraft_sendpass: "{{ lookup('file', 'secret/inspircd_links_minecraft_sendpass') }}"
inspircd_modules_cloak_key: "{{ lookup('file', 'secret/inspircd_modules_cloak_key') }}"
