---
- name: Set hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  notify:
  - hostname
- name: Configure networking
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644
  notify:
  - networking
- name: Configure hosts
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0640
- name: Configure resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
- name: Add iptables script
  copy: src=iptables dest=/etc/network/if-up.d/iptables owner=root group=root mode=0740
- name: Make iptables.d
  file: path=/etc/iptables.d state=directory owner=root group=root mode=0740
- name: Configure IPv4 firewall
  copy: src=0common.rules dest=/etc/iptables.d/0common.rules owner=root group=root mode=0640
  notify:
  - iptables
- name: Configure IPv6 firewall
  copy: src=ip6tables.conf dest=/etc/ip6tables.conf owner=root group=root mode=0640
  notify:
  - iptables
- name: Set apt sources
  copy: src={{ item }} dest=/etc/apt/{{ item }} owner=root group=root mode=0644
  with_items:
  - sources.list
  - apt.conf
- name: Install common packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - ethtool
  - ntp
  - openssh-server
- name: Add SSH banner
  copy: src=ssh_banner dest=/etc/ssh/banner owner=root group=root mode=0644
- name: Configure sshd
  template: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
  - sshd
- name: Configure ntpd
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:
  -  ntp
